### ISSUE TITLE
[Meta] Add unit tests to the package

### ISSUE THREAD

**Issue by ALanguillaume** [Edouard-Legoupil/kobocruncher#6]
# Add unit tests to the package

## How to contribute

1 - Make sure you have clone the package on your computer
2 - Checkout this issue and spot a function that has no unit tests yet
3 - Open an issue to add unit tests to that function
4 - Go back to your local {kobocruncher} and PULL ! to make sure to work from the latest version of main
5 - Create a new branch `<number>-iissue-add-test-<function-name>`
6 - Add a unit test 
7 - Inflate and make sure the check is passing
8 - Make a commit
9 - Make a PR and assigned to Edouard
10 - When the PR is merged Edouard updates the list below

## TODO list off all functions to add unit tests to

- [ ] app_kobocruncher
- [ ] kobo_anonymise
- [ ] kobo_clean
- [ ] kobo_cruncher
- [ ] kobo_data
- [ ] kobo_dico
- [ ] kobo_frame
- [ ] kobo_indicator
- [ ] kobo_likert
- [ ] kobo_prepare_form
- [ ] kobo_ridl
- [ ] label_choiceset
- [ ] label_varhint
- [ ] label_varname
- [ ] plot_correlation
- [ ] plot_header
- [ ] plot_integer
- [ ] plot_integer_cross
- [ ] plot_likert
- [ ] plot_select_multiple
- [ ] plot_select_multiple_cross
- [ ] plot_select_one
- [ ] plot_select_one_cross
- [ ] plot_text
- [ ] template_1_exploration
